apiVersion: v1
kind: Service
metadata:
    name: bharadwajnavitasbankingv
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
    - port: 443 
    selector:
        app: bharadwajnavitasbankingv
