apiVersion : v1
kind: Service
metadata:
  name: bharadwajnavitasbankingv
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: bharadwajnavitasbankingv
  type: LoadBalancer
