apiVersion: v1
kind: Service
metadata:
    name: bharadwajnavitasbankingv
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 80
    selector:
        app: bharadwajnavitasbankingv
